# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Echo304 Blog"
email: "echo3042@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Blog about Javascript, CS, SW
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://echo304.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  echo304

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown:    kramdown
highlighter: rouge

# Build settings
kramdown:
  input: GFM

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"
excerpt_separator: <!--excerpt_separator-->